# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller build: the workbench as something you can hand to somebody.

**One-dir, not one-file.** One-file unpacks the whole bundle into a temporary
directory on every launch, which for a 200 MB analysis toolchain is a visible
pause and, worse, moves `__file__` somewhere new each run. One-dir puts the
executable next to `tools/` and `cases/` where an operator expects them, and it
is the layout `ringforge.resources.app_root()` is written against.

**What is in here and what is not.** The engine, the GUI, the five shipped data
groups, and nothing that cannot be redistributed. Procmon, Autorunsc, Sysmon,
FLOSS, capa, FakeNet and the downloaded YARA set stay out -- `bootstrap_tools.ps1`
installs them into `tools/` beside the executable, and their absence is
reported as a coverage gap the way it always was.

Build with `python -m PyInstaller ringforge.spec --noconfirm`.
"""

import subprocess
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files, copy_metadata

SPEC_DIR = Path(SPECPATH).resolve()


# ---------------------------------------------------------------------------
# Build-time identity
# ---------------------------------------------------------------------------
# A frozen build has no git history and no distribution metadata, so
# `analyzer_provenance()` would report version and commit as null -- an
# unidentifiable verdict, from the envelope that exists to make verdicts
# identifiable. Stamp both here and let `verdict.provenance._baked` read them.

def _git(*args: str) -> str:
    try:
        out = subprocess.run(["git", "-C", str(SPEC_DIR), *args],
                             capture_output=True, text=True, timeout=10, check=False)
        return out.stdout.strip() if out.returncode == 0 else ""
    except Exception:
        return ""


def _version() -> str:
    # Read the one declaration rather than duplicating it here.
    text = (SPEC_DIR / "pyproject.toml").read_text(encoding="utf-8")
    for line in text.splitlines():
        if line.startswith("version = "):
            return line.split("=", 1)[1].strip().strip('"')
    return ""


commit = _git("rev-parse", "HEAD")
dirty = bool(_git("status", "--porcelain"))
build_info = SPEC_DIR / "ringforge" / "_build_info.py"
build_info.write_text(
    '"""Generated by ringforge.spec at build time. Not tracked; do not edit."""\n'
    "\n"
    f'VERSION = {_version()!r}\n'
    f'COMMIT = {(commit + ("+dirty" if dirty else "")) or None!r}\n',
    encoding="utf-8",
)


# ---------------------------------------------------------------------------
# What travels with the code
# ---------------------------------------------------------------------------
datas = []

# `ringforge/_data`: the logo, the Procmon filter configs, the authored YARA
# rules. Resolved through `importlib.resources`, so they must land under
# `ringforge/` in the bundle, which is what collect_data_files does.
datas += collect_data_files("ringforge")

# `importlib.metadata` is how provenance reports the library versions that
# change what a collector can see. Without the metadata directories those all
# read null, which is the same failure `rule_file_count` was.
# Keep this list equal to `verdict.provenance._TRACKED` plus the package
# itself. The first build shipped `lief` the extension module without its
# metadata, so provenance reported `lief: null` -- library absent -- for a
# library that was sitting right there. That is `rule_file_count` again.
for dist in ("ringforge-workbench", "yara-python", "pefile",
             "psutil", "PyYAML", "requests", "lief"):
    try:
        datas += copy_metadata(dist)
    except Exception:
        # An optional dependency that is not installed reports as absent
        # rather than failing the build. That is the documented posture.
        pass

hiddenimports = [
    # Imported by name through the step table rather than at module scope.
    "static_triage_engine.ioc_extract",
    "static_triage_engine.pe_meta",
    "static_triage_engine.dotnet_meta",
    "static_triage_engine.dotnet_summary",
    "static_triage_engine.lief_meta",
    "ringforge.resources",
]

# Bench-only weight. The emulator, the corpus surveys and the PDF path live in
# `scripts/`, which is not shipped; pulling their dependencies in would roughly
# double the bundle for code no executable can reach.
excludes = [
    "matplotlib", "scipy", "numpy", "pandas",
    "unicorn", "capstone",
    "weasyprint",
    "pytest", "_pytest",
    "IPython", "notebook",
]


common = dict(
    pathex=[str(SPEC_DIR)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
)

# Two entry points, one bundle. Deliberately *not* MERGE: that rewrites the
# dependent analysis into a reference expecting its own COLLECT and its own
# dist directory, which silently produced a bundle with the GUI in it and no
# `ringforge.exe` at all. Two full analyses share one COLLECT instead; they
# resolve the same dependencies to the same destinations, so the duplicates
# collapse rather than conflict.
gui_analysis = Analysis([str(SPEC_DIR / "gui" / "__main__.py")], **common)
cli_analysis = Analysis([str(SPEC_DIR / "ringforge" / "cli.py")], **common)

gui_pyz = PYZ(gui_analysis.pure)
cli_pyz = PYZ(cli_analysis.pure)

# **The names match `[project.scripts]`**, so the commands are the same whether
# the workbench was installed or unzipped. They also have to differ by more than
# case: `RingForge.exe` and `ringforge.exe` are one filename on Windows, and the
# first build of this spec quietly produced a bundle containing only one of them.
#
# `console=False` for the window: a tkinter app started from Explorer should not
# raise a console behind it. `console=True` for the CLI, whose whole contract is
# that `--json` owns stdout and diagnostics go to stderr.
gui_exe = EXE(
    gui_pyz, gui_analysis.scripts, [],
    exclude_binaries=True,
    name="ringforge-gui",
    icon=None,
    console=False,
    debug=False,
    strip=False,
    upx=False,
)

cli_exe = EXE(
    cli_pyz, cli_analysis.scripts, [],
    exclude_binaries=True,
    name="ringforge",
    icon=None,
    console=True,
    debug=False,
    strip=False,
    upx=False,
)

COLLECT(
    gui_exe, gui_analysis.binaries, gui_analysis.datas,
    cli_exe, cli_analysis.binaries, cli_analysis.datas,
    strip=False,
    upx=False,
    name="RingForge",
)


# ---------------------------------------------------------------------------
# Post-build: the things a redistributable bundle owes people
# ---------------------------------------------------------------------------
# **This runs after COLLECT because COLLECT is what creates `dist/`.** Files
# handed to PyInstaller as `datas` land under `_internal/`, which is the right
# place for code and the wrong place for a licence somebody is meant to read.
#
# The first build of this spec shipped nine third-party libraries and not one
# line of their licence text, including this project's own MIT `LICENSE`. MIT
# and BSD both require the copyright notice to accompany a binary
# distribution, so that was not a tidiness problem.

import shutil
from importlib.metadata import distribution, PackageNotFoundError

DIST = SPEC_DIR / "dist" / "RingForge"

#: Distributions whose code is inside the bundle. Kept explicit rather than
#: discovered, so that adding a dependency is a decision about licensing too.
LICENSED = (
    "pefile", "psutil", "PyYAML", "requests", "yara-python",
    "pillow", "lief", "certifi", "charset-normalizer", "idna", "urllib3",
)

#: Redistributable third-party tools, copied in beside the executable so the
#: existing `app_root() / "tools"` lookup finds them with no code change.
#: Both are Apache-2.0. Everything else the workbench drives -- Procmon,
#: Autorunsc, Sysmon, Npcap -- may not be redistributed at all, which is why
#: only these two are here. See docs/TOOL_SETUP.md.
#: Whole directories, not named binaries: the upstream release archives carry
#: LICENSE.txt beside the executable, and Apache-2.0 requires that it travel
#: with the binary. Copying the directory keeps them together by construction.
#: **`tools/capa-rules` is deliberately not here.** Three reasons, and the
#: third settled it: capa's standalone build embeds its own rules, so the copy
#: is redundant for the capa in this bundle; the rule paths run to 132
#: characters relative, so a user unzipping into a deep folder blows MAX_PATH
#: and gets a partial extract with no useful error; and the directory is
#: gitignored, so a CI build never has it and a local build did -- the two
#: produced different bundles. `bootstrap_capa_rules.ps1` installs them for
#: anyone who wants a rules directory of their own.
VENDORED = ("tools/floss", "tools/capa")


def _stage_licences() -> None:
    out = DIST / "licenses"
    out.mkdir(parents=True, exist_ok=True)
    manifest = ["Third-party licence text for the libraries inside this bundle.",
                "Generated by ringforge.spec at build time.",
                "See THIRD-PARTY-NOTICES.md for the full record, including the",
                "external tools this bundle does NOT contain.",
                ""]
    for name in LICENSED:
        try:
            dist = distribution(name)
        except PackageNotFoundError:
            manifest.append(f"{name}: NOT INSTALLED at build time; not bundled")
            continue
        copied = 0
        for entry in dist.files or []:
            if not any(k in Path(str(entry)).name.upper()
                       for k in ("LICENSE", "COPYING", "NOTICE")):
                continue
            source = Path(dist.locate_file(entry))
            if not source.is_file():
                continue
            target = out / name / Path(str(entry)).name
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
            copied += 1
        declared = (dist.metadata.get("License-Expression")
                    or dist.metadata.get("License") or "see project metadata")
        if copied:
            manifest.append(f"{name} {dist.version} ({declared}): licenses/{name}/")
        else:
            # `lief` is the live example: Apache-2.0 upstream, no licence file
            # in its wheel. Recorded rather than quietly omitted.
            manifest.append(
                f"{name} {dist.version} ({declared}): no licence file in the "
                f"distribution; see the upstream project")
    (out / "MANIFEST.txt").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    print(f"  staged licence text for {len(LICENSED)} distributions")


#: Files copied to the bundle root as (source, name-in-the-bundle).
#:
#: `docs/INSTALL.md` becomes `README.md` because somebody who downloads only
#: the zip has no repository to read, and the first thing they look for after
#: unzipping is a README. `TOOL_SETUP.md` travels with it since the install
#: guide sends them there for the tools that cannot be redistributed.
NOTICES = (
    ("LICENSE", "LICENSE"),
    ("THIRD-PARTY-NOTICES.md", "THIRD-PARTY-NOTICES.md"),
    ("docs/INSTALL.md", "README.md"),
    ("docs/TOOL_SETUP.md", "TOOL_SETUP.md"),
)


def _stage_notices() -> None:
    for relative, name in NOTICES:
        source = SPEC_DIR / relative
        if source.is_file():
            shutil.copy2(source, DIST / name)
            print(f"  staged {name}")
        else:
            print(f"  WARNING: {relative} not found; the bundle ships without it")


def _stage_tools() -> None:
    # Written by the release workflow: which upstream release each tool came
    # from and its SHA256. A local build has none and ships without it.
    record = SPEC_DIR / "tools" / "VENDORED.txt"
    if record.is_file():
        (DIST / "tools").mkdir(parents=True, exist_ok=True)
        shutil.copy2(record, DIST / "tools" / "VENDORED.txt")
        print("  staged tools/VENDORED.txt")

    for relative in VENDORED:
        source = SPEC_DIR / relative
        if not source.is_dir():
            # Absence is reportable, not fatal: a local build without capa
            # still produces a working bundle that reports capa as missing.
            print(f"  skipped {relative} (not present)")
            continue
        # Redistributing an Apache-2.0 binary means shipping its licence, so
        # this refuses rather than warns. A warning in build output is a
        # warning nobody reads at upload time, and the failure mode is
        # publishing someone else's binary with no licence attached.
        #
        # The release workflow fetches both tools from the upstream archive,
        # which carries LICENSE.txt. A hand-placed `floss.exe` does not, and is
        # skipped here -- the bundle then reports the tool as missing, which is
        # true and harmless, instead of shipping it bare.
        licensed = any(
            any(k in f.name.upper() for k in ("LICENSE", "COPYING", "NOTICE"))
            for f in source.rglob("*") if f.is_file()
        )
        if not licensed:
            print(f"  REFUSED {relative}: no licence text beside the binary")
            continue

        shutil.copytree(source, DIST / relative, dirs_exist_ok=True)
        print(f"  staged {relative}")


if DIST.is_dir():
    print("Staging redistributable content:")
    _stage_licences()
    _stage_notices()
    _stage_tools()
else:
    print(f"WARNING: {DIST} does not exist; nothing staged")
