# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller build: the workbench as something you can hand to somebody.

**One-dir, not one-file.** One-file unpacks the whole bundle into a temporary
directory on every launch, which for a 200 MB analysis toolchain is a visible
pause and, worse, moves `__file__` somewhere new each run. One-dir puts the
executable next to `tools/` and `cases/` where an operator expects them, and it
is the layout `ringforge.resources.app_root()` is written against.

**What is in here and what is not.** The engine, the GUI, the five shipped data
groups, and nothing that cannot be redistributed. Procmon, Autorunsc, Sysmon,
FLOSS, capa, FakeNet and the downloaded YARA set stay out -- `bootstrap_tools.ps1`
installs them into `tools/` beside the executable, and their absence is
reported as a coverage gap the way it always was.

Build with `python -m PyInstaller ringforge.spec --noconfirm`.
"""

import subprocess
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files, copy_metadata

SPEC_DIR = Path(SPECPATH).resolve()


# ---------------------------------------------------------------------------
# Build-time identity
# ---------------------------------------------------------------------------
# A frozen build has no git history and no distribution metadata, so
# `analyzer_provenance()` would report version and commit as null -- an
# unidentifiable verdict, from the envelope that exists to make verdicts
# identifiable. Stamp both here and let `verdict.provenance._baked` read them.

def _git(*args: str) -> str:
    try:
        out = subprocess.run(["git", "-C", str(SPEC_DIR), *args],
                             capture_output=True, text=True, timeout=10, check=False)
        return out.stdout.strip() if out.returncode == 0 else ""
    except Exception:
        return ""


def _version() -> str:
    # Read the one declaration rather than duplicating it here.
    text = (SPEC_DIR / "pyproject.toml").read_text(encoding="utf-8")
    for line in text.splitlines():
        if line.startswith("version = "):
            return line.split("=", 1)[1].strip().strip('"')
    return ""


commit = _git("rev-parse", "HEAD")
dirty = bool(_git("status", "--porcelain"))
build_info = SPEC_DIR / "ringforge" / "_build_info.py"
build_info.write_text(
    '"""Generated by ringforge.spec at build time. Not tracked; do not edit."""\n'
    "\n"
    f'VERSION = {_version()!r}\n'
    f'COMMIT = {(commit + ("+dirty" if dirty else "")) or None!r}\n',
    encoding="utf-8",
)


# ---------------------------------------------------------------------------
# What travels with the code
# ---------------------------------------------------------------------------
datas = []

# `ringforge/_data`: the logo, the Procmon filter configs, the authored YARA
# rules. Resolved through `importlib.resources`, so they must land under
# `ringforge/` in the bundle, which is what collect_data_files does.
datas += collect_data_files("ringforge")

# `importlib.metadata` is how provenance reports the library versions that
# change what a collector can see. Without the metadata directories those all
# read null, which is the same failure `rule_file_count` was.
# Keep this list equal to `verdict.provenance._TRACKED` plus the package
# itself. The first build shipped `lief` the extension module without its
# metadata, so provenance reported `lief: null` -- library absent -- for a
# library that was sitting right there. That is `rule_file_count` again.
for dist in ("ringforge-workbench", "yara-python", "pefile",
             "psutil", "PyYAML", "requests", "lief"):
    try:
        datas += copy_metadata(dist)
    except Exception:
        # An optional dependency that is not installed reports as absent
        # rather than failing the build. That is the documented posture.
        pass

hiddenimports = [
    # Imported by name through the step table rather than at module scope.
    "static_triage_engine.ioc_extract",
    "static_triage_engine.pe_meta",
    "static_triage_engine.dotnet_meta",
    "static_triage_engine.dotnet_summary",
    "static_triage_engine.lief_meta",
    "ringforge.resources",
]

# Bench-only weight. The emulator, the corpus surveys and the PDF path live in
# `scripts/`, which is not shipped; pulling their dependencies in would roughly
# double the bundle for code no executable can reach.
excludes = [
    "matplotlib", "scipy", "numpy", "pandas",
    "unicorn", "capstone",
    "weasyprint",
    "pytest", "_pytest",
    "IPython", "notebook",
]


common = dict(
    pathex=[str(SPEC_DIR)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
)

# Two entry points, one bundle. Deliberately *not* MERGE: that rewrites the
# dependent analysis into a reference expecting its own COLLECT and its own
# dist directory, which silently produced a bundle with the GUI in it and no
# `ringforge.exe` at all. Two full analyses share one COLLECT instead; they
# resolve the same dependencies to the same destinations, so the duplicates
# collapse rather than conflict.
gui_analysis = Analysis([str(SPEC_DIR / "gui" / "__main__.py")], **common)
cli_analysis = Analysis([str(SPEC_DIR / "ringforge" / "cli.py")], **common)

gui_pyz = PYZ(gui_analysis.pure)
cli_pyz = PYZ(cli_analysis.pure)

# **The names match `[project.scripts]`**, so the commands are the same whether
# the workbench was installed or unzipped. They also have to differ by more than
# case: `RingForge.exe` and `ringforge.exe` are one filename on Windows, and the
# first build of this spec quietly produced a bundle containing only one of them.
#
# `console=False` for the window: a tkinter app started from Explorer should not
# raise a console behind it. `console=True` for the CLI, whose whole contract is
# that `--json` owns stdout and diagnostics go to stderr.
gui_exe = EXE(
    gui_pyz, gui_analysis.scripts, [],
    exclude_binaries=True,
    name="ringforge-gui",
    icon=None,
    console=False,
    debug=False,
    strip=False,
    upx=False,
)

cli_exe = EXE(
    cli_pyz, cli_analysis.scripts, [],
    exclude_binaries=True,
    name="ringforge",
    icon=None,
    console=True,
    debug=False,
    strip=False,
    upx=False,
)

COLLECT(
    gui_exe, gui_analysis.binaries, gui_analysis.datas,
    cli_exe, cli_analysis.binaries, cli_analysis.datas,
    strip=False,
    upx=False,
    name="RingForge",
)
